# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 466f2efda2bfe213132b64712dc1a2ade7d40b8f79b2ddffcee35451a865a2a95bbbac48a060c63e2170dc13e2393d61cdb6cedcb7260f723c9a22ea3768dc74

test:
  secret_key_base: d605f17872154e075ad5581f7b32cea34de28f13ad160234a871a69a8c26b22c7f3643e5d6671f02f3a3aecc355238527a3c54f2c2e86213934476609ef567fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
